### ISSUE TITLE
handling failed ssh-connections

### ISSUE THREAD

**Issue by dforrer** [lxxxvi/raspifarm-cluster-mgmt#1]
```
farmer@raspifarm-master:~ $ cluster stats all
ssh: connect to host 192.168.17.15 port 22: No route to host
/home/farmer/cluster/lib/cluster/slave.rb:36:in `calculate_cpu_usage': undefined method `split' for nil:NilClass (NoMethodError)
    from /home/farmer/cluster/lib/cluster/slave.rb:29:in `analyze'
    from /home/farmer/cluster/lib/cluster/slave.rb:18:in `stats'
    from /home/farmer/cluster/lib/cluster/services/stat_service.rb:13:in `block in call'
    from /home/farmer/cluster/lib/cluster/services/scope_service.rb:13:in `block in each'
    from /home/farmer/cluster/lib/cluster/services/scope_service.rb:13:in `each'
    from /home/farmer/cluster/lib/cluster/services/scope_service.rb:13:in `each'
    from /home/farmer/cluster/lib/cluster/services/stat_service.rb:12:in `call'
    from /home/farmer/cluster/lib/cluster.rb:49:in `execute'
    from /home/farmer/cluster/lib/cluster.rb:16:in `call'
    from /home/farmer/cluster/bin/cluster.rb:10:in `<main>'
```

**Comment by dforrer** [comment]
This issue still exists here...

```
farmer@raspifarm-master:~ $ cluster stats all
ssh: connect to host 192.168.17.15 port 22: No route to host
/home/farmer/cluster/lib/cluster/node.rb:32:in `remote_backticks': Command 'top -bn2 -d 0.2 | grep '^%Cpu' | tail -1;top -bn1 | grep '^KiB Mem'' failed to execute on host 192.168.17.15 (RuntimeError)
    from /home/farmer/cluster/lib/cluster/slave.rb:17:in `stats'
    from /home/farmer/cluster/lib/cluster/services/stat_service.rb:13:in `block in call'
    from /home/farmer/cluster/lib/cluster/services/scope_service.rb:13:in `block in each'
    from /home/farmer/cluster/lib/cluster/services/scope_service.rb:13:in `each'
    from /home/farmer/cluster/lib/cluster/services/scope_service.rb:13:in `each'
    from /home/farmer/cluster/lib/cluster/services/stat_service.rb:12:in `call'
    from /home/farmer/cluster/lib/cluster.rb:53:in `execute'
    from /home/farmer/cluster/lib/cluster.rb:16:in `call'
    from /home/farmer/cluster/bin/cluster.rb:11:in `<main>'
```
